version: '3.8'

services:

  kubedium-control:
    image: ghcr.io/kubedium/kubedium:latest
    container_name: kubedium-control
    privileged: true
    command: ["--role", "control-plane"]
    networks:
      - k8s-net
    restart: unless-stopped
    mem_limit: 1500m
    cpus: 1.5
    healthcheck:
      test: ["CMD", "kubectl", "get", "nodes"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  kubedium-worker:
    image: ghcr.io/kubedium/kubedium:latest
    container_name: kubedium-worker
    privileged: true
    command: ["--role", "worker", "--join", "kubedium-control"]
    depends_on:
      kubedium-control:
        condition: service_healthy
    networks:
      - k8s-net
    restart: unless-stopped
    mem_limit: 1200m
    cpus: 1.0
    healthcheck:
      test: ["CMD", "pgrep", "kubelet"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  jenkins:
    image: jenkins/jenkins:lts-jdk11
    container_name: jenkins
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Kolkata
    networks:
      - k8s-net
    restart: unless-stopped
    mem_limit: 1500m
    cpus: 1.5
    depends_on:
      kubedium-worker:
        condition: service_healthy

volumes:
  jenkins_home:

networks:
  k8s-net:
    driver: bridge
